[CSLD-65] PVSS certificates clarification
input-output-hk/cardanodocs.com pull request #1
Opened 2017-04-28 12:52 UTC by denisshevchenko

DO NOT MERGE YET!

2017-04-28 23:41 UTC, rockbmb approved these changes

2017-04-28 23:41 UTC, rockbmb commented on _docs/2017-01-19-glossary.md
> +## Richmen
Richmen -> Richman

2017-04-29 14:43 UTC, rockbmb requested changes
@staenrey can you review this please?

2017-04-29 14:43 UTC, rockbmb commented on _docs/technical/2017-02-10-pvss.md
> +Initially, all stakeholders with stake enough for participation in randomness generation (we call them [richmen](/glossary/#richmen)) [have their own certificates](https://github.com/input-output-hk/
"with stake enough"
maybe you wanted "with enough stake"?

2017-05-01 12:05 UTC, staenrey approved these changes
Changes made

2017-05-02 00:21 UTC, rockbmb approved these changes

2017-05-02 00:21 UTC, merged