[CSLD-54] Add description of Peer Data
input-output-hk/cardanodocs.com pull request #3
Opened 2017-04-28 17:14 UTC by ChShersh

This PR add description of Peer Data. Though this PR also will change some `time-warp` layer documentation because after https://github.com/serokell/time-warp-nt/pull/54 merges to `master` some things change.

2017-04-29 10:04 UTC, staenrey approved these changes
Reviewed, changes added in a commit

2017-04-29 13:48 UTC, ChShersh commented
@staenrey Thanks! Could you please review once again? I've added new information.

2017-04-29 14:25 UTC, rockbmb requested changes
Great work @ChShersh, many examples.
@staenrey please review the newer commit, afterwards I'll take another look and merge.

2017-04-29 14:25 UTC, rockbmb commented on _docs/technical/protocols/2017-01-01-application-level.md
> +can be changed. So nodes should be aware of the protocol the other peer is running.
"the other peer"? This is too specific, use the plural "peers".

2017-04-29 14:25 UTC, rockbmb commented on _docs/technical/protocols/2017-01-13-binary.md
> +Usually `ByteString`s in `cardano` encoded with length encoded as variable
This sentence is a bit strange, cc @staenrey.

2017-05-01 10:18 UTC, staenrey commented on _docs/technical/protocols/2017-01-01-application-level.md
> +can be changed. So nodes should be aware of the protocol the other peer is running.
done

2017-05-01 10:18 UTC, staenrey commented on _docs/technical/protocols/2017-01-13-binary.md
> +Usually `ByteString`s in `cardano` encoded with length encoded as variable
changed the sentence

2017-05-08 21:44 UTC, rockbmb approved these changes

2017-05-08 21:45 UTC, merged