[CSLD-105] Update HD wallets chapter
input-output-hk/cardanodocs.com pull request #37
Opened 2017-07-22 22:04 UTC by Martoon-00

Brought doc up to date with regard to recent features + applied some cosmetic changes

2017-07-23 16:46 UTC, dniku requested changes
Please fix these grammatical issues.

2017-07-23 16:46 UTC, Pastafarianist commented on _docs/technical/2017-05-14-hd-wallets.md
> +<!-- For subscripts symbols: https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts -->
If you are on Linux, you can configure XCompose to type in sub- and superscripts directly. Check out this: https://help.ubuntu.com/community/ComposeKey

2017-07-23 16:46 UTC, Pastafarianist commented on _docs/technical/2017-05-14-hd-wallets.md
> +-   `i <= 2³¹ - 1` for **non-hardened** keys
Since we're into Unicode here: `≤`

2017-07-23 16:46 UTC, Pastafarianist commented on _docs/technical/2017-05-14-hd-wallets.md
> +Wallet storage is extended to store list of **wallets**. Each wallet corresponds
_a_ list of wallets

2017-07-23 16:46 UTC, Pastafarianist commented on _docs/technical/2017-05-14-hd-wallets.md
>  to single root secret key (backed up by mnemonics and encrypted with spending
_a_ single key

2017-07-23 16:46 UTC, Pastafarianist commented on _docs/technical/2017-05-14-hd-wallets.md
> +-   generate arbitrary amount of **addresses**
_an_ arbitrary _number_ of addresses

2017-07-23 17:27 UTC, Martoon-00 commented on _docs/technical/2017-05-14-hd-wallets.md
> +<!-- For subscripts symbols: https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts -->
Sugoi!

2017-07-28 18:14 UTC, denisshevchenko requested changes

2017-07-28 18:14 UTC, denisshevchenko commented on _docs/technical/2017-05-14-hd-wallets.md
>  For **Non-hardened** keys
Why "Non-hardened" with capital letter? :-)

2017-07-28 18:14 UTC, denisshevchenko commented
And please add a dots at the end of all complete sentences. :-)

2017-07-28 19:54 UTC, Martoon-00 commented
Which ones, for instance?

2017-08-03 11:01 UTC, denisshevchenko approved these changes

2017-08-03 12:40 UTC, staenrey approved these changes
grammar checked

2017-08-03 13:01 UTC, merged